name: test-workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  call-workflow-passing-data:
    uses: mpearon/public-workflows/.github/workflows/vsce-extension-BuildPublish.yml@main
    secrets:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
